---
title: Controllo del flusso di esecuzione e gestione degli errori
slug: Web/JavaScript/Guida/Controllo_del_flusso_e_gestione_degli_errori
tags:
  - Controllo di flusso
  - Guide
  - JavaScript
  - Principianti
  - 'l10n:priority'
translation_of: Web/JavaScript/Guide/Control_flow_and_error_handling
---
<div>{{jsSidebar("JavaScript Guide")}} {{PreviousNext("Web/JavaScript/Guide/Grammar_and_types", "Web/JavaScript/Guide/Loops_and_iteration")}}</div>

<p class="summary">JavaScript prevede un insieme di istruzioni compatto, specifico per il controllo del flusso di esecuzione, che si può utilizzare per aggiungere un'elevata interattività alle proprie applicazioni. Questo capitolo fornisce una panoramica su queste istruzioni.</p>

<p>Il <a href="/en-US/docs/Web/JavaScript/Reference/Statements">JavaScript reference</a> contiene dettagli esaustivi sulle istruzioni di questo capitolo. Il carattere punto e virgola (<code>;</code>) è usato per separare le varie istruzioni del codice JavaScript.</p>

<p>Ogni espressione JavaScript è a sua volta un'istruzione. Si veda a riguardo <a href="/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators">Espressioni ed operatori</a> per una completa descrizione delle espressioni.</p>

<h2 id="Costrutto_di_blocco">Costrutto di blocco</h2>

<p>Un costrutto fondamentale è il <strong>blocco</strong>, usato per raggruppare insieme più istruzioni, delimitato da un paio di parentesi graffe ({}):</p>

<pre class="syntaxbox notranslate">{
  istruzione_1;
  istruzione_2;
  .
  .
  .
  istruzione_n;
}
</pre>

<h3 id="Esempi"><strong>Esempi</strong></h3>

<p>Il blocco è comunemente usato assieme alle istruzioni per il controllo del flusso (e.g. <code>if</code>, <code>for</code>, <code>while</code>).</p>

<pre class="brush: js notranslate">while (x &lt; 10) {
  x++;
}
</pre>

<p>Qui, <code>{ x++; }</code> rappresenta un blocco.</p>

<p><strong>Importante</strong>: JavaScript prima di ECMAScript2015 <strong>non</strong> aveva la visibilità di blocco. Le variabili definite nel blocco hanno una visibilità a livello di funzione o di script in cui sono contenute e l'effetto di assegnare loro un valore persiste oltre il blocco stesso. Cioè il blocco non definisce un campo di visibilità. I blocchi "Indipendenti" ("Standalone" blocks) in JavaScript possono dare un risultato differente da quello che avrebbero prodotto in C o in Java. Per esempio:</p>

<pre class="brush: js notranslate">var x = 1;
{
  var x = 2;
}
console.log(x); // produce 2
</pre>

<p>Risulta 2 perché l'istruzione di definizione <code>var x</code> dentro il blocco ha lo stesso campo di visibilità dell'istruzione <code>var x</code> al di fuori del blocco. Mentre in C o Java, il codice equivalente avrebbe prodotto 1.</p>

<p>A partire da ECMAScript2015, la dichiarazione di variabile con l'istruzione <code>let</code> ha visibilità di blocco. Si veda il riferimento a {{jsxref("Statements/let", "let")}} per ulteriori informazioni.</p>

<h2 id="Costrutti_Condizionali">Costrutti Condizionali</h2>

<p>Un costrutto condizionale è un insieme di istruzioni che vengono eseguite se una specifica condizione risulta vera. JavaScript prevede due costrutti condizionali: <code>if...else</code> e <code>switch</code>.</p>

<h3 id="Costrutto_if...else"><code>Costrutto if...else</code></h3>

<p>Si usa il costrutto <code>if</code> per eseguire un blocco di istruzioni se una condizione logica è vera. Si usa la clausola opzionale <code>else</code> per eseguire istruzioni nel caso in cui la stessa condizione sia falsa. Un costrutto <code>if...else</code> si presenta come qui sotto:</p>

<pre class="brush: js notranslate">if (condizione) {
  istruzioni_se_vera_la_condizione;
} else {// opzionale
  istruzioni_se_falsa_la_condizione;
}</pre>

<p>Qui la <code>condizione</code> è qualsiasi espressione che sia valutabile come vera oppure falsa (<code>true</code> o <code>false</code>). Si veda il riferimento a <a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean#Description">Boolean</a> per una spiegazione su cosa possa essere valutabile come <code>true</code> o <code>false</code>. Se la <code>condizione</code> viene valutata <em>true</em>, <code>istruzioni_se_vera_la_condzione</code> verrà eseguito, altrimenti verrà eseguito <code>istruzioni_se_falsa_la_condzione</code>. <code>istruzioni_se_vera_la_condzione</code> e <code>istruzioni_se_falsa_la_condzione</code> possono essere qualsiasi istruzione, incluso un altro <code>if</code>.</p>

<p>Si possono pure combinare le istruizioni <code>else if</code> per testare molteplici condizioni in sequenza, come il seguente codice dimostra:</p>

<pre class="syntaxbox notranslate">if (condizione_1) {
  istruzione_1;
} else if (condizione_2) {
  istruzione_2;
} else if (condizione_n) {
  istruzione_n;
} else {
  ultima_istruzione;
}
</pre>

<p>Nel caso di condizioni plurime solo la prima che sia valutata come vera sarà eseguita. Per eseguire più istruzioni si devono raggruppare in un blocco (<code>{ ... }</code>) . In generale è buona pratica usare un blocco specialmente se si usano <code>if</code> annidati:</p>

<pre class="syntaxbox notranslate">if (condizione) {
  istruzione_1_eseguita_se_vera_la_condizione;
  istruzione_2_eseguita_se_vera_la_condizione;
  ...
} else {
  istruzione_3_eseguita_se_falsa_la_condizione;
  istruzione_4_eseguita_se_falsa_la_condizione;
  ...
}
</pre>

<div>Non è consigliabile usare la semplice assegnazione in una espressione condizionale, perché l'assegnamento potrebbe essere confuso con il segno di uguaglianza quando si dia un'occhiata rapida al codice. Ad esempio, non si usi il seguente codice:</div>

<div></div>

<pre class="example-bad brush: js notranslate">if (x = y) {// questa è una assegnazione
  /* istruzioni qui */
}</pre>

<p>Se si deve proprio usare un assegnamento in una espressione condizionale è pratica comune aggiungere un paio di parentesi tonde attorno all'assegnamento. Per esempio:</p>

<pre class="brush: js notranslate">if ((x = y)) {
  /* istruzioni qui */
}
</pre>

<h4 id="Valori_valutabili_a_false">Valori valutabili a false</h4>

<p>I seguenti valori si valutano a <code>false</code> (sono anche detti {{Glossary("Falsy")}} value):</p>

<ul>
 <li><code>false</code></li>
 <li><code>undefined</code></li>
 <li><code>null</code></li>
 <li><code>0</code></li>
 <li><code>NaN</code></li>
 <li>la stringa vuota (<code>""</code>)</li>
</ul>

<p>Tutti gli altri valori, inclusi gli oggetti, saranno valutati a <code>true</code> in una istruzione condizionale.</p>

<p>Non si confonda il valori primitivi booleani <code>true</code> e <code>false</code> con i valori <code>true</code> e <code>false</code> dell'oggetto {{jsxref("Boolean")}}. Ad esempio:</p>

<pre class="brush: js notranslate">var b = new Boolean(false);

if (b) // questa condizione è valutata a true
       // perché 'b' in questo caso è un oggetto
       // e si sa che tutti gli oggetti sono valutati a true

if (b == true) // mentre questa a false,
               // perché si va a prelevare il contenuto dell'oggetto 'b' che è false
</pre>

<h4 id="Esempi_2"><strong>Esempi</strong></h4>

<p>Nell'esempio a seguire la funzione <code>controllaDati</code> ritorna <code>true</code> se il numero di caratteri contenuti nella proprietà <code>value</code> dell'oggetto <code>Text (treCaratteri)</code> è tre, altrimenti mostra un popup di alert e, infine, ritorna il valore <code>false</code>.</p>

<pre class="brush: js notranslate">function controllaDati() {
  if (document.form1.treCaratteri.value.length == 3) {
    return true;
  } else {
    alert("Immetti esattemente tre caratteri. " +
    document.form1.treCaratteri.value + " non è valido.");
    return false;
  }
}
</pre>

<h3 id="Costrutto_switch"><code>Costrutto switch</code></h3>

<p>Un costrutto <code>switch</code> permette ad un programma di valutare un'espressione e tentare di trovare la corrispondenza esatta tra il valore risultante dalla valutazione dell'espressione e l'etichetta specificata nella clausola <code>case</code>. Se si incontra una corrisopondenza il programma eseguirà le istruzioni associate. Un costrutto <code>switch</code> si presenta  come nell'esempio qui sotto riportato:</p>

<pre class="syntaxbox notranslate">switch (espressione) {
  case etichetta_1:
    istruzione_1
    [break;]// opzionale
  case etichetta_2:
    istruzione_2
    [break;]
    ...
  default:
    istruzioni_di_default
    [break;]
}
</pre>

<p>Il programma cerca la prima corrispondenza tra il valore ottentuto della valutazione dell'<code>espressione </code>e l'etichetta nella clausola <code>case</code>, poi trasferisce il controllo al corpo della medesima clausola eseguendo le istruzioni relative. Se non è stata trovata alcuna corrispondeza il programma va alla clausola opzionale <code>default</code> e, se la trova, esegue le istruizioni ad essa relative. Se non è stata data alcuna clausola <code>default</code> il programma continuerà con l'istruzione successiva al blocco <code>switch</code>. La clausola <code>default</code> è l'ultima che appare nel blocco<code> switch</code>, ma questa è una convenzione non la regola.</p>

<p>Il <code>break</code> opzionale, associato con ogni clausola <code>case,</code> assicura che il programma esca dal blocco <code>switch</code> una volta eseguite le istruzioni associate alla clausola e continui la sua esecuzione all'istruzione che segue il costrutto <code>switch</code>. Se il <code>break</code> è omesso il programma continua la sua esecuzione all'istruzione successiva nello stesso costrutto <code>switch</code>, ciò significa che eseguirà le istruzioni associate alla clausola <code>case/default</code> (se ci sono) successiva a quella appena terminata.</p>

<h4 id="Esempi_3"><strong>Esempi</strong></h4>

<p>Nel seguente esempio, se la variabile <code>tipidifrutto</code> contiene "Banane", il programma cercherà la corrispondente clausola <code>case "Banane"</code> ed eseguirà le istruzioni associate. Quando incontra il <code>break</code>, il porgramma esce dallo <code>switch</code> ed esegue l'istruzione successiva al blocco di <code>switch</code>. Se, invece, il <code>break</code> fosse stato omesso le istuzioni collegate con la clausola <code>case "Ciliege"</code> sarebbero state eseguite.</p>

<pre class="brush: js notranslate">switch (tipidifrutta) {
  case "Arance":
    console.log("Le Arance sono a €0.59 il chilo.");
    break;
  case "Mele":
    console.log("Le mele sono a €0.32 il chilo.");
    break;
  case "Banane":
    console.log("Le Banane sono €0.48 il chilo.");
    break;
  case "Ciliege":
    console.log("Le ciliege sono s €3.00 il chilo.");
    break;
  case "Mango":
    console.log("Il Mango è è €0.56 il chilo.");
    break;
  case "Papaia":
    console.log("Il Mango e la Papaia sono a €2.79 il chilo.");
    break;
  default:
    console.log("Spiacenti, abbiano terminato " + tipidifrutta + ".");
}
console.log("C'è qualcos'altro che ti piace?");</pre>

<h2 id="Costrutti_di_gestione_delle_Eccezioni">Costrutti di gestione delle Eccezioni</h2>

<p>Si può sollevare/generare un'eccezione attraverso l'istruzione <code>throw</code> e si possono gestire usando il costrutto <code>try...catch</code>.</p>

<ul>
 <li><a href="#Istruzione_throw">istruzione throw</a></li>
 <li><a href="#trt_catch">costrutto try...catch</a></li>
</ul>

<h3 id="Tipi_di_eccezione">Tipi di eccezione</h3>

<p>Quasi ogni tipo di oggetto può essere usato per sollevare/generare un'eccezione JavaScript. Tuttavia non tutti gli oggetti utili a questo scopo sono creati in modo eguale. Mentre è abbastanza comune usare numeri o stringhe per indicare un errore, è più efficace usare uno dei tipi di eccezione specificatamente creati a questo scopo:</p>

<ul>
 <li><a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects#Fundamental_objects">eccezioni di ECMAScript</a></li>
 <li>{{domxref("DOMException")}} e {{domxref("DOMError")}}</li>
</ul>

<h3 id="Istruzione_throw_2"><code><a id="Istruzione_throw" name="Istruzione_throw"></a>Istruzione throw</code></h3>

<p>Si usa l'istruzione <code>throw</code> per sollevare/generare un'eccezione. Quando si genera un'eccezione va specificata un'espressione che produca un valore da usarsi come eccezione:</p>

<pre class="syntaxbox notranslate">throw espressione;
</pre>

<p>Si può usare una qualsiasi espressione con l'istruzione <code>throw </code>e non solamente espressioni di un certo tipo. Il seguente pezzo di codice lo dimostra:</p>

<pre class="brush: js notranslate">throw "Errore2";  // tipo String
throw 42;         // tipo Number
throw true;       // tipo Boolean
throw {toString: function() { return "Sono un oggetto!"; } };
</pre>

<div class="note"><strong>Note:</strong> Si può specificare un oggetto quando si genera un'eccezione. Si può poi far riferimento alle proprietà dell'oggetto nel blocco <code>catch</code>. Il seguente esempio crea un oggetto <code>myUserException</code> del tipo <code>UserException</code> e lo usa nell'istruzione throw.</div>

<pre class="brush: js notranslate">// Crea un oggetto di tipo UserException
function UserException(messaggio) {
  this.message = messaggio;
  this.name    = "UserException";
}

// Sovrascrive il metodo toString() affinché l'oggetto
// dia una descrizione di se stesso al momento di usarlo come stringa.
// (e.g. come messaggio nella console degli errori)
UserException.prototype.toString = function() {
  return this.name + ': "' + this.message + '"';
}

// Crea un'istanza dell'oggetto e lo usa nell'istruzione throw
throw new UserException("Valore troppo alto!);</pre>

<h3 id="Costrutto_try...catch_..._finally"><code><a id="trt_catch" name="trt_catch"></a>Costrutto try...catch (... finally)</code></h3>

<p>Il costrutto <code>try...catch</code> racchiude un blocco di istruzioni, che potrebbero generare un'eccezione, e specifica uno o più azioni per gestire l'eccezione che potrebbe essere sollevata. Se viene sollevata un'eccezione il costrutto <code>try...catch</code> la cattura.</p>

<p>Il costrutto <code>try...catch</code> è costituito da un blocco <code>try</code>, che contiene a sua volta uno o più istruzioni, e da al più (vedi nota più sotto) un blocco <code>catch</code>, contenenti istruzioni per gestire l'eccezione che eventulmente sarà sollevata all'interno del blocco <code>try</code>.  Cioè si vorrebbe che il blocco <code>try</code> fosse eseguito senza errori, ma se non fosse possibile si vuole che l'esecuzione passi al blocco <code>catch</code>. Se un'istruzione contenuta nel blocco (o in una funzione chiamata all'interno del blocco) <code>try</code> genera un'eccezione, il controllo passa immediatamente al blocco <code>catch</code>. Se nessuna eccezione è sollevata all'interno del blocco <code>try</code>, il blocco <code>catch</code> è semplicemente ignorato. Il blocco <code>finally (</code>opzionale se c'è il blocco <code>catch</code>, ma necessario se manca quest'utimo) è eseguito subito dopo l'esecuzione dei blocchi <code>try<font face="Open Sans, Arial, sans-serif">/</font></code><code>catch</code>, ma prima di una qualsiasi istruzione che segua gli stessi <code>try...catch...finally</code>.</p>

<div class="note">
<p>In realtà il browser Firefox è in grado di suppostare i blocchi <code>catch</code> condizionati, oltre quello incondizionato, rendendo virtualmeente illimitata la definizione di più di un blocco <code>catch </code>per uno stesso blocco<code> try</code>. Tuttavia questa caratteristica non è standard e se ne scoraggia l'uso, si veda a proposito la referenza {{jsxref("Statements/try...catch", "try...catch")}}.</p>
</div>

<p>L'esempio che segue usa il costrutto di <code>try...catch</code>. L'esempio chiama una funzione che ritorna il nome del mese estratto da un array grazie al parametro <code>mo</code> passato alla funzione. Se il valore passato non corrispondesse al numero di mese consentito (tra 1 e 12), un'eccezione verrebbe sollevata col valore <code>"numeroMeseNonValido"</code><code> </code>e il blocco <code>catch</code> assegnerebbe alla variabile <code>nomeDelMese</code> il vaore di "<code>sconoscuto"</code>.</p>

<pre class="brush: js notranslate">function getNomeDelMese(mo) {
  mo = mo - 1; // Sistema il numero del mese (1 = Gen, 12 = Dic)
  var mesi = ["Gen","Feb","Mar","Apr","Mag","Giu","Lug",
                "Ago","Set","Ott","Nov","Dic"];
  if (mesi[mo]) {
    return mesi[mo];
  } else {
    throw "numeroMeseNonValido"; //l'istruzione throw è usata qui
  }
}

try { // blocco try
  nomeDelMese = getNomeDelMese(mese); // la funzione potrebbe sollevare un'eccezione
}
catch (eccezione) {
  nomeDelMese = "sconosciuto";
  logDegliErrori(eccezione); // Passa l'eccezione a un gestore -&gt; una propria funzione
</pre>

<h4 id="Il_blocco_catch">Il blocco <code>catch</code></h4>

<p>Si può usare il blocco <code>catch</code> per gestire le eccezioni che possono essere generate nel blocco <code>try</code>.</p>

<pre class="syntaxbox notranslate">catch (catchID) {
  // istruzioni
}
</pre>

<p>Il blocco <code>catch</code> viene specificato un identificatore (<code>catchID</code> nel precedente esempio) che conterrà il valore specificato nell'istruzione <code>throw.</code> Si può usare questo identificatore per ottenere informazione ulteriori circa l'eccezione che è stata generata. JavaScript crea questo identificatore quando si entra nel blocco <code>catch.</code> L'identificatore è valido solo per la durata in esecuzione del blocco <code>catch </code>stesso, infatti usciti dal blocco <code>catch</code> termina la sua esistenza e non è più disponibile.</p>

<p>Per esempio, il seguente codice solleva un'eccezione. Quando l'eccezione si realizza il controllo passa al blocco <code>catch</code>.</p>

<pre class="brush: js notranslate">try {
  throw "miaEccezione"; // genera una eccezione
}
catch (eccezione) { // "eccezione" è l'identificatore con conterrà
  // l'oggetto usato nell'istruzione thrown, in questo caso la stringa "miaEccezione"

  // istruzioni che gestiscono l'eccezione
  gestisciErrori(eccezione); // passa l'oggetto eccezione al gestore
}
</pre>

<h4 id="Il_blocco_finally">Il blocco <code>finally</code></h4>

<p>Il blocco <code>finally</code> contiene istruzioni che vengono eseguite subito dopo i blocchi <code>try</code> ed eventualmente <code>catch</code>, ma prima di ogni altra istruzione che segua il costrutto <code>try...catch...finally</code>. Il blocco <code>finally</code> è eseguito indipendentemente dal fatto che un'eccezione sia o meno generata. Se un'eccezione viene sollevata le istruzioni nel blocco <code>finally</code> saranno eseguite anche se il blocco <code>catch</code> corrispondente la gestisce.</p>

<p>Si può usare il blocco <code>finally</code> per permettere agli script di terminare elegantemente in presenza di un'eccezione, ad esempio, se si deve liberare una risorsa che lo script trattiene. Il seguente esempio apre un file e lo usa (JavaScript lato server permette di accedere al file system). Se si solleva un'eccezione mentre il file è aperto il blocco <code>finally</code> chiude il file prima che lo script termini/fallisca.</p>

<pre class="brush: js notranslate">apriMioFile();
try {
  ScriviMioFile(dati); //Qui si può verificare un'eccezione/errore
} catch(e) {
  gestisciErrore(e); // Se avviene un errore lo si gestisce
} finally {
  chiudiMioFile(); // chiude comunque la risorsa
}
</pre>

<p>Se il blocco <code>finally</code> ritorna un valore questo diviene il valore ritornato dall'intero costrutto <code>try-catch-finally</code> a dispetto di qualsiasi valore eventualmente ritornato dai blocchi <code>try/c</code><code>atch</code>:</p>

<pre class="brush: js notranslate">function f() {
  try {
    console.log(0);
    throw "fasulla";
  } catch(e) {
    console.log(1);
    return true; // quasta istruzione di ritorno è sospesa
                 // finché il blocco finally non termina
    console.log(2); // istruzione non raggiungibile
  } finally {
    console.log(3);
    return false; // sovrascrive il precedente "return"
    console.log(4); // istruzione non raggiungibile
  }
  // "return false" è eseguito ora
  console.log(5); // istruzione non raggiungibile
}
f(); // nel log a console troviamo stampato: 0, 1, 3 e false
</pre>

<p>La sovrascrittura dei valori di ritorno, da parte del blocco <code>finally,</code> colpisce anche le eccezioni generate e/o ri-generate dentro il blocco <code>catch</code>:</p>

<pre class="brush: js notranslate">function f() {
  try {
    throw "fasulla";
  } catch(e) {
    console.log('catturata l\'eccezione interna "fasulla"');
    throw e; // Quasta istruzione throw è sospesa
             // finché il blocco finally non termina
  } finally {
    return false; // sovrascrive il precedente "throw"
  }
  // "return false" è eseguita ora
}

try {
  f();
} catch(e) {
  // Questo blocco non sarà mai raggiunto in quanto l'istruzione
  // throw dentro il blocco catch (vedi più sopra) è sovrascritta
  // dal return della clausola finally
  console.log('catturata l\'eccezione esterna "fasulla"');
}

// OUTPUT
// catturata l'eccezione interna "fasulla"</pre>

<h4 id="try...catch_innestati">try...catch innestati</h4>

<p>Si possono annidare <code>try...catch.</code> Se un blocco <code>try...catch</code> interno non ha il blocco <code>catch </code>(in questo caso è d'obbligo che ci sia il blocco <code>finally</code>, anche vuoto, altrimenti si ha un errore sintattico), il blocco catch, del costrutto <code>try...catch</code> che lo racchiude, catturerà l'eventuale eccezione.</p>

<pre class="brush: js notranslate">try{// try-catch esterno
  try{
   // try-finally interno
    throw "eccezione fasulla";
  }
  // Manca il blocco catch, ma deve esserci il blocco finally
  finally{
    // vuoto
  }
}
catch(e){
  // Viene catturata l'eccezione sollevata dal blocco più interno
  console.log("cattura esterna: " + e);
}

//nella console sarà stampato: "cattura esterna: eccezione fasulla"</pre>

<h3 id="Utilizzo_degli_oggetti_Error">Utilizzo degli oggetti <code>Error</code></h3>

<p>A seconda del tipo di errore se si è in grado di usare le proprietà '<code>name</code>' e '<code>message</code>' si può avere un messaggio più ricco. '<code>name</code>' fornisce la classe generale dell'Error (e.g., 'DOMException' o 'Error'), mentre '<code>message</code>' generalmente fornisce un messaggio più conciso rispetto al convertire l'oggetto corrispondente all'errore in una stringa.</p>

<p>Se si crea una propria eccezione affiché ci si avvantaggi di queste proprietà (come nel caso, ad esempio, del blocco <code>catch</code> che non discrimini tra l'oggetto rappresentante la propria eccezione e quello di sistema) si può usare il costruttore dell'oggetto Error:</p>

<pre class="brush: js notranslate">function faiQualcosaSoggettaAdErrore () {
  if (codiceCheProduceUnErrore()) {
    throw (new Error('Il Messaggio'));
  } else {
    faiQualcosaPerOttenereUnEorreDiJavascript();
  }
}
....
try {
  faiQualcosaSoggettaAdErrore();
} catch (e) {
  console.log(e.name);    // Scrive a console: 'Error'
  console.log(e.message); // Scrive a console: 'Il Messaggio' o un messaggio di errore di JavaScript)
}</pre>

<h2 id="I_Promise">I Promise</h2>

<p>A partire da ECMAScript2015, JavaScript acquisisce il supporto agli oggetti {{jsxref("Promise")}} permettendo di controllare l'esecuzione di operazioni in modo differito e asincrono.</p>

<p>Un <code>Promise</code> può essere in uno di questi stati:</p>

<ul>
 <li><em>pending</em>: stato iniziale, non <em>fulfilled</em> o <em>rejected</em>.</li>
 <li><em>fulfilled</em>: operazione risucita.</li>
 <li><em>rejected</em>: operazione fallita.</li>
 <li><em>settled</em>: il Promise è alternativamente <em>fulfilled</em> o <em>rejected</em>, ma non <em>pending</em>.</li>
</ul>

<p><img alt="" src="https://mdn.mozillademos.org/files/8633/promises.png" style="height: 297px; width: 801px;"></p>

<h3 id="Caricare_unimmagine_con_XHR">Caricare un'immagine con XHR</h3>

<p>Un esempio di semplice utilizzo di un <code>Promise</code> e <code><a href="/en-US/docs/Web/API/XMLHttpRequest">XMLHttpRequest</a></code> per caricare un'immagine è disponibile nel repository <a href="https://github.com/mdn/promises-test/blob/gh-pages/index.html">promise-test</a> di MDN GitHub. Si può anche<a href="http://mdn.github.io/promises-test/"> vedere in azione</a>. Ogni passo  è commentato e ti permette di seguire il Promise e l'architettura XHR da vicino. Qui, invece, la versione non commentata che mostra l'utilizzo del <code>Promise</code> per darti un'idea del suo funzionamento:</p>

<pre class="brush: js notranslate">function caricaImmagine(url) {
  return new Promise(function(resolve, reject) {
    var request = new XMLHttpRequest();
    request.open('GET', url);
    request.responseType = 'blob';
    request.onload = function() {
      if (request.status === 200) {
        resolve(request.response);
      } else {
        reject(Error('L\'immagine non è stata caricata con successo; codice di errore:'
                     + request.statusText));
      }
    };
    request.onerror = function() {
      reject(Error('C\'è stato un errore di connessione'));
    };
    request.send();
  });
}</pre>

<p>Per informazioni più dettagliate si veda la pagina di riferimento relativa al {{jsxref("Promise")}}.</p>

<div>{{PreviousNext("Web/JavaScript/Guide/Grammar_and_types", "Web/JavaScript/Guide/Loops_and_iteration")}}</div>
