---
title: EvalError
slug: Web/JavaScript/Reference/Global_Objects/EvalError
tags:
  - Error
  - EvalError
  - JavaScript
  - помилка
translation_of: Web/JavaScript/Reference/Global_Objects/EvalError
---
<div>{{JSRef}}</div>

<p>Об'єкт <strong><code>EvalError</code></strong> позначає помилку, пов'язану з використанням глобальної функції {{jsxref("Global_Objects/eval", "eval()")}}. Цей виняток більше не викидається у JavaScript, однак, об'єкт <code>EvalError</code> залишено для сумісності.</p>

<h2 id="Синтаксис">Синтаксис</h2>

<pre class="syntaxbox"><code>new EvalError([<var>message</var>[, <var>fileName</var>[, <var>lineNumber</var>]]])</code></pre>

<h3 id="Параметри">Параметри</h3>

<dl>
 <dt><code>message</code></dt>
 <dd>Необов'язковий. Зрозумілий людині опис помилки.</dd>
 <dt><code>fileName</code> {{non-standard_inline}}</dt>
 <dd>Необов'язковий. Ім'я файлу, код з якого спричинив виняток.</dd>
 <dt><code>lineNumber</code> {{non-standard_inline}}</dt>
 <dd>Необов'язковий. Номер рядка в коді, що спричинив виняток.</dd>
</dl>

<h2 id="Властивості">Властивості</h2>

<dl>
 <dt><code>EvalError.prototype</code></dt>
 <dd>Дозволяє додавати властивості до об'єктів <code>EvalError</code>.</dd>
</dl>

<h2 id="Методи">Методи</h2>

<p>Сам <code>EvalError</code> не має власних методів, але успадковує деякі методи через ланцюжок прототипів.</p>

<h2 id="Екземпляри_EvalError">Екземпляри EvalError</h2>

<h3 id="Властивості_2">Властивості</h3>

<div>{{page('/uk/docs/Web/JavaScript/Reference/Global_Objects/EvalError/prototype', 'Властивості')}}</div>

<h3 id="Методи_2">Методи</h3>

<div>{{page('/uk/docs/Web/JavaScript/Reference/Global_Objects/EvalError/prototype', 'Методи')}}</div>

<h2 id="Приклади">Приклади</h2>

<p><code>EvalError</code> не використовується у нинішній специфікації ECMAScript, а отже, не викидатиметься під час виконання. Однак, сам об'єкт залишається для зворотної сумісності з більш ранніми версіями специфікації.</p>

<h3 id="Створення_EvalError">Створення EvalError</h3>

<pre class="brush: js">try {
  throw new EvalError('Привіт', 'someFile.js', 10);
} catch (e) {
  console.log(e instanceof EvalError); // true
  console.log(e.message);              // "Привіт"
  console.log(e.name);                 // "EvalError"
  console.log(e.fileName);             // "someFile.js"
  console.log(e.lineNumber);           // 10
  console.log(e.columnNumber);         // 0
  console.log(e.stack);                // "@Scratchpad/2:2:9\n"
}
</pre>

<h2 id="Специфікації">Специфікації</h2>

<table class="standard-table">
 <tbody>
  <tr>
   <th scope="col">Специфікація</th>
  </tr>
  <tr>
   <td>{{SpecName('ESDraft', '#sec-native-error-types-used-in-this-standard-evalerror', 'EvalError')}}</td>
  </tr>
 </tbody>
</table>

<h2 id="Сумісність_з_веб-переглядачами">Сумісність з веб-переглядачами</h2>

<div>
<div>


<p>{{Compat("javascript.builtins.EvalError")}}</p>
</div>
</div>

<h2 id="Див._також">Див. також</h2>

<ul>
 <li>{{jsxref("Error")}}</li>
 <li>{{jsxref("Global_Objects/eval", "eval()")}}</li>
</ul>
