---
title: URIError
slug: Web/JavaScript/Reference/Global_Objects/URIError
tags:
  - Error
  - JavaScript
  - URIError
  - помилка
translation_of: Web/JavaScript/Reference/Global_Objects/URIError
---
<div>{{JSRef}}</div>

<p>Об'єкт <code><strong>URIError</strong></code> позначає помилку, що виникає при хибному використанні глобальної функції, що працює з URI.</p>

<h2 id="Синтаксис">Синтаксис</h2>

<pre class="syntaxbox"><code>new URIError([<var>message</var>[, <var>fileName</var>[, <var>lineNumber</var>]]])</code></pre>

<h3 id="Параметри">Параметри</h3>

<dl>
 <dt><code>message</code> {{optional_inline}}</dt>
 <dd>Необов'язковий. Зрозумілий людині опис помилки.</dd>
 <dt><code>fileName</code> {{optional_inline}} {{non-standard_inline}}</dt>
 <dd>Необов'язковий. Ім'я файлу, код з якого спричинив виняток.</dd>
 <dt><code>lineNumber</code> {{optional_inline}} {{non-standard_inline}}</dt>
 <dd>Необов'язковий. Номер рядка в коді, що спричинив виняток.</dd>
</dl>

<h2 id="Опис">Опис</h2>

<p><code>URIError</code> викидається, коли глобальним функціям, що працюють з URI, передається неправильно сформований URI.</p>

<h2 id="Властивості">Властивості</h2>

<dl>
 <dt><code>URIError.prototype</code></dt>
 <dd>Дозволяє додавати властивості до об'єктів <code>URIError</code>.</dd>
</dl>

<h2 id="Методи">Методи</h2>

<p>Сам <code>URIError</code> не має власних методів, але успадковує деякі методи через ланцюжок прототипів.</p>

<h2 id="Екземпляри_URIError">Екземпляри <code>URIError</code></h2>

<h3 id="Властивості_2">Властивості</h3>

<div>{{page('/uk/docs/Web/JavaScript/Reference/Global_Objects/URIError/prototype', 'Властивості')}}</div>

<h3 id="Методи_2">Методи</h3>

<div>{{page('/uk/docs/Web/JavaScript/Reference/Global_Objects/URIError/prototype', 'Методи')}}</div>

<h2 id="Приклади">Приклади</h2>

<h3 id="Перехоплення_URIError">Перехоплення <code>URIError</code></h3>

<pre class="brush: js">try {
  decodeURIComponent('%');
} catch (e) {
  console.log(e instanceof URIError) // true
  console.log(e.message)             // "malformed URI sequence"
  console.log(e.name)                // "URIError"
  console.log(e.fileName)            // "Scratchpad/1"
  console.log(e.lineNumber)          // 2
  console.log(e.columnNumber)        // 2
  console.log(e.stack)               // "@Scratchpad/2:2:3\n"
}
</pre>

<h3 id="Створення_URIError">Створення <code>URIError</code></h3>

<pre class="brush: js">try {
  throw new URIError('Привіт', 'someFile.js', 10);
} catch (e) {
  console.log(e instanceof URIError) // true
  console.log(e.message)             // "Привіт"
  console.log(e.name)                // "URIError"
  console.log(e.fileName)            // "someFile.js"
  console.log(e.lineNumber)          // 10
  console.log(e.columnNumber)        // 0
  console.log(e.stack)               // "@Scratchpad/2:2:9\n"
}
</pre>

<h2 id="Специфікації">Специфікації</h2>

<table class="standard-table">
 <tbody>
  <tr>
   <th scope="col">Специфікація</th>
  </tr>
  <tr>
   <td>{{SpecName('ESDraft', '#sec-native-error-types-used-in-this-standard-urierror', 'URIError')}}</td>
  </tr>
 </tbody>
</table>

<h2 id="Сумісність_з_веб-переглядачами">Сумісність з веб-переглядачами</h2>

<div>


<p>{{Compat("javascript.builtins.URIError")}}</p>
</div>

<h2 id="Див._також">Див. також</h2>

<ul>
 <li>{{jsxref("Error")}}</li>
 <li>{{jsxref("Global_Objects/decodeURI", "decodeURI()")}}</li>
 <li>{{jsxref("Global_Objects/decodeURIComponent", "decodeURIComponent()")}}</li>
 <li>{{jsxref("Global_Objects/encodeURI", "encodeURI()")}}</li>
 <li>{{jsxref("Global_Objects/encodeURIComponent", "encodeURIComponent()")}}</li>
</ul>
